### ISSUE TITLE
featurize_dataframe mishandles features that are equally sized numpy arrays

### ISSUE THREAD

**Issue by kylebystrom** [hackingmaterials/matminer#100]
When BaseFeaturizer.featurize_dataframe() is called for a featurizer which returns equal-dimension
numpy arrays (such as OrbitalFieldMatrix and the in-dev ManyBodyTensor), the code exits in error,
as shown in the Python code and output attached in testfeat.txt. The reason for this is that featurize_dataframe joins the features into a numpy array, which is interpreted as a multidimensional array if and only if each element of the array has the same length. If the features are single values, the array is 1D, and if they are variable-length arrays, the array is interpreted as a 1D collection of other objects. The `assign` call in `featurize_dataframe` does not handle multidimensional arrays.

A possible fix is shown in testfeat.py, in which a dataframe is featurized by adding a Series initialized
from a list of features. As shown in testnew.txt, there does not seem to be a significant speed difference between these methods. I apologize if the fix is underthought; I am not familiar with the reasoning for the original design, so I may well be missing something.

[testfeat.txt](https://github.com/hackingmaterials/matminer/files/1594941/testfeat.txt)
[testnew.txt](https://github.com/hackingmaterials/matminer/files/1594942/testnew.txt)

**Comment by WardLT** [comment]
Hello @kylebystrom ,

Thanks for catching this problem! I'm made a PR that incorporate the change you suggested, which I thought was spot-on.

Do those changes look like they will work for you?

**Comment by kylebystrom** [comment]
Yes, that fix looks great! Thank you.
