### ISSUE TITLE
unit tests for sample data loaders

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#103]
@kylebystrom 

this will make sure the package_data correctly contains the CSV files needed for sample data sets (as @kylebystrom found out was an issue in the past)

putting this issue here as a reminder so we don't forget about this

**Comment by kylebystrom** [comment]
Hi @computron,
I made a couple improvements to the datasets module and unit tests, but it appears that even the old unit tests should fail with a FileNotFoundError if the CSV files aren't there, correct?

**Comment by computron** [comment]
(this was completed)
