### ISSUE TITLE
some cleanups to sample dataframes

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#108]
@kylebystrom can you help clean up some of the sample dataframes?

* Don't need an "idx" column (there is already a material_id column that serves as an index)
* Actually make the "material_id" the index column of the dataframe - see for example the ``index_col`` parameter of ``pd.read_csv`` (you'll notice there is no extraneous index column after doing this).
* if ``volume`` is volume per site, rename to ``volume_per_site``. If it's not per site, probably remove it.
* reorder the columns to be in the following order

1. The index column ("material_id")
2. The formula/composition
3. Other parameters that succintly describe the input structure (nsites, volume, space_group, etc)
4. The actual structure column itself
5. Simple (float) output data - band gap, K_VRH, etc.
6. Complex (vector, tensor) output data - elastic tensor, piezoelectric tensor, etc.
7. Any extra metadata (cif, poscar, etc) that is essentially redundant info with structure

**Comment by kylebystrom** [comment]
Will do!

**Comment by computron** [comment]
(this was completed)
