### ISSUE TITLE
support for grouped DataFrames in featurizers

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#113]
There is a way to group columns in DataFrames which makes things look much prettier and more organized. See for example this example from Patrick Huck in MP:

![2018-01-23 10 42 57 am](https://user-images.githubusercontent.com/986759/35293959-323e54d6-002a-11e8-8fa6-843d338c51a9.png)

It would be nice if:

* sample dataframes included grouped columns (e.g., an "outputs" group, a "metadata" group, an "inputs" group) ( @kylebystrom )
* the featurize_dataframe() method could featurize into a group so that all features for a particular featurizer (or multifeaturizer) were grouped together.

**Comment by computron** [comment]
(maybe @WardLT @JFChen3 for the latter improvements to featurize_dataframe() ?)

**Comment by WardLT** [comment]
Nice! I didn't realize you could group columns this way. The code looks decently straightforward. I could give it a shot for marking which featurizer a feature comes from for MultiFeaturizer.

**Comment by computron** [comment]
@ardunn do you consider this complete? if so can you close?

**Comment by ardunn** [comment]
@computron This is definitely not complete. I removed it from a previous PR because it made the PR too complicated. It is on the "todos" though
