### ISSUE TITLE
too many presets

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#128]
Some of the featurizers have a large amount of presets, all of which are doing essentially the same thing. Here's one from a recent PR, although there were many before this of the same form (some committed by me).

```
+        if preset == "VoronoiNN":
 +            return ChemicalSRO(VoronoiNN())
 +        elif preset == "JMolNN":
 +            return ChemicalSRO(JMolNN())
 +        elif preset == "MinimumDistanceNN":
 +            return ChemicalSRO(MinimumDistanceNN())
 +        elif preset == "MinimumOKeeffeNN":
 +            return ChemicalSRO(MinimumOKeeffeNN())
 +        elif preset == "MinimumVIRENN":
 +            return ChemicalSRO(MinimumVIRENN())
 +        else:
 +            raise RuntimeError('Unknown preset.')
```

We should:

1. Clean up the code to shorten it, using something like this:
https://stackoverflow.com/questions/4821104/python-dynamic-instantiation-from-string-name-of-a-class-in-dynamically-imported

It will also allow us to automatically support new NearNeighbor algorithms ,etc.

2. Consider having more guidance to presets. e.g. instead of just a billion presets, to do more like what the ElementProperty presets and do and just give a few "vetted" suggestions.

**Comment by nisse3000** [comment]
@computron, sounds sensible.  I'll take care about the example you gave.

**Comment by nisse3000** [comment]
@computron, done (in my fork).  I'm waiting with the pull request until @shyuep has released the next pymatgen version so that the additions of new and optimized OPs will also be part of that PR.

**Comment by nisse3000** [comment]
See PR #136.

**Comment by computron** [comment]
Closing for now. Note that another option is that if a preset is "strong" enough (we really advocate for that preset, or there is a paper that advocates for that combination of settings that can be cited) we can create a new featurizer for it. That new featurizer can basically just call the old featurizer with the chosen parameter set. It should help in discoverability of that preset.
