### ISSUE TITLE
Minor Bug in CrystalSiteFingerprint.featurize()

### ISSUE THREAD

**Issue by YunxingZuo** [hackingmaterials/matminer#137]
I try to use featurize method in CrystalSiteFingerprint class, but met this bug:
TypeError: __init__() got an unexpected keyword argument 'target'

Possible solution:
In line 484 in featurizer/site.py, vnn = VoronoiNN(cutoff=self.cutoff_radius, targets=target), because no 'target' parameter in VoronoiNN
In line 486 in featurizer/site.py, n_w = vnn.get_voronoi_polyhedra(struct, idx)
because no 'use_weights' parameter in VoronoiNN.get_voronoi_polyhedra method

**Comment by computron** [comment]
Thanks! I just pushed the changes via: 1b6207b81b0596e0aa88d041cc96c1e612822ae4

Should be reflected in the next release
