### ISSUE TITLE
ElectronegativityDiff failures

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#143]
See

```
# TODO: this featurizer should fail gracefully for compounds with no clear anions (e.g., metals where all elements have zero oxidation) - returning either NaN or zero.
```

matminer.featurizers.composition.ElectronegativityDiff

**Comment by WardLT** [comment]
I think `NaNs` make the most sense for this class, as the features are not applicable to metals. But, this opens a question: Should we return `NaN`s or raise an Exception (and rely on the `ignore_errors` of `featurize_dataframe`)? 

I'm in favor of the Exception route (and am currently implementing it), as it gives more feedback on why the featurizer is returning `NaN`s.

**Comment by computron** [comment]
I agree, Exception is good, it should just be informative
