### ISSUE TITLE
Should featurize_dataframe have an exceptions_encountered() variable?

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#154]
Let's say you run featurize_dataframe with ignore_errors=True. After finishing featurization, you might want to just see what errors were encountered. If the BaseFeaturizer had an attribute/function called exceptions_encountered() perhaps it could return all the exceptions encountered during the previous featurize_dataframe() call.

Implementation would be simple - just create the variable, reset it at the beginning of the featurize_dataframe, and use traceback module to add the string version of each Exception to a list.

Another way to do it would be to add another parameter called ``return_errors`` to featurize_dataframe(). If ``ignore_errors`` and ``return_errors`` are both true, then featurize_dataframe would change its return type to be a tuple of the new dataframe and a list of errors encountered. This would avoid having a state variable for the previous errors.

Maybe other ways to do it - but the point would be to be able to see a list of errors encountered during featurize_dataframe with ignore_errors = True.

**Comment by ardunn** [comment]
Sure, I think this would be tremendously useful! 

I would personally lean towards the second option (a `return_errors` arg). However instead of changing the return type, what do you think about adding a "(name of featurizer) errors " column to the dataframe? Then you can just print the relevant rows of the dataframe to see what rows did not featurize well (in an organized fashion).

**Comment by computron** [comment]
Sounds good to me! But I would wait until the BaseFeaturizer changes are finished and merged before implementing this, otherwise we're gong to end up with merge conflicts all over.

**Comment by computron** [comment]
Closed via https://github.com/hackingmaterials/matminer/pull/165
