### ISSUE TITLE
citrination-client and plotly should be optional requirements

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#16]
@saurabh02 

Commit 948fe5e96ff51469d54914fe0dacc072aa217037 makes citrination-client and plotly required libraries of matminer. This should not be the case. We can think of a typical use case of matminer as someone that has a spreadsheet of data and wants to add descriptors (composition or structure) to it and then run a data mining model. Neither plotly nor citrination-client is needed for that (although pymatgen and pandas are). If a library is extremely lightweight or robust then it's also usually OK to put it in requirements.

As far as I can tell you added the requirements to get a unit test to pass. But the way to do it is to fix the unit test, not require additional libraries. e.g., pymatgen contains examples on how to write unittests with optional libraries (you raise a SkipTest if the library is not installed). Can you try it this way?
 
Note also that if you do add requirements, you should also pin the version as per the other requirements.

**Comment by saurabh02** [comment]
Thanks for your comment @computron. Yes you are right in that I added those back to get the unit test to pass. I can certainly look into making them optional and skipping them in the unit tests, but a quick question before doing that - if and when a user wants to utilize a utility of matminer that makes use of these packages, eg: the Citrine data retrieval/plotting functionalities, are you saying it's better to show a "library not found" error at that time instead of forcing install right from the beginning along with matminer?

**Comment by computron** [comment]
Hi @saurabh02 

I think it's a good question. In my book, there are a few reasons to go with optional dependency:

- the disk size of the dependency is large
- the dependency is difficult to install, e.g., cannot be auto-installed
- the dependency has some chance of breaking the auto-install (i.e., someone who wants to ```pip install matminer``` gets an error during the installation of the dependency - so they can't install matminer automatically, even if they never planned on using that sub-feature).
- The dependency has other dependencies that have one of the above characteristics.

Based on those criteria, I don't see a reason to make citrination-client optional and we can keep it as required so the user has access to the functionality without extra effort. If we find that the dependency breaks one of those criteria in the future, we should make it optional.

We can keep plotly for the same reasons. Again, if it starts breaking things we'll make it optional.

**Comment by saurabh02** [comment]
Thanks for your thoughts @computron !
