### ISSUE TITLE
PRDF (PartialRadialDistributionFunction) featurizer: params in fit() vs init()

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#161]
For PRDF featurizer, why put ``included_elems()`` and ``excluded_elems()`` in the fit() function rather than a constructor argument?

matminer.featurizers.structure.PartialRadialDistributionFunction#fit

Note that it should be technically allowed by sklearn to have fit_params, so the current implementation is not incorrect, but just curious why not put it in the constructor.

**Comment by WardLT** [comment]
In retrospect, I think these parameters would be better off in the constructor. That way, you need to provide them at fit time every time you fit the PRDF.

I'm having trouble figuring out an argument for keeping them in the fit function that I'd be happy with. I'll issue a quick PR to move them to init().
