### ISSUE TITLE
Put all matminer examples in the matminer_examples repo

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#174]
@montoyjh 

Can you put all matminer examples (e.g. ipynb notebooks) in this repo:

https://github.com/hackingmaterials/matminer_examples

It will prevent bloat of the main matminer repo while having a central place for examples. Feel free to add anything that's missing to that repo or a directory structure, for now I just put a bare-bones version.

Make sure you find all .ipynb notebooks in matminer, e.g., there are some hiding in the data_retrieval module

**Comment by computron** [comment]
(also update the docs with the new locations of the examples)

**Comment by montoyjh** [comment]
Yes, I like this solution.  Should be able to update by early next week.

**Comment by computron** [comment]
pretty sure this is done, closing
