### ISSUE TITLE
Yaml files not showing up in Pypi package

### ISSUE THREAD

**Issue by shyamd** [hackingmaterials/matminer#178]
Installing matminer with pip works fine, but upon use certain yaml files don't seem to be there. This was a classic issue with atomate and I don't remember what fixed it. 
For instance:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/shyamd/.virtualenvs/py3/lib/python3.6/site-packages/matminer/featurizers/cn_target_motif_op.yaml

**Comment by computron** [comment]
@nisse3000 

if you add YAML files (or any non .py) files to matminer you need to also update:

- MANIFEST.in (note that recursive-include doesn't always work, so having explicit include is usually better)
- setup.py (the package_data variable)

I just did this via 37a06d604d3df9a8990177e1fd208d19825c041c

I will push a new release tomorrow, please re-open this issue if you still see issues after that.
