### ISSUE TITLE
PlotlyFig xy issues

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/matminer#181]
Issues include:
- its hard to just plot a set of lines with colors specified by an array of colors. The markers change colors but the *lines* do not change colors

EDIT: removed colorbar issue and moved to #188

**Comment by ardunn** [comment]
Also xy does not have a "limits" arg for its axes. Although a limits arg can either go in constructor or in .xy, probably better if it just goes in xy because that will be the most common use case by far, and other plotting methods being restricted by limits can cause huge issues + complexity (eg what are the limits on a heatmap)

Limits can be done with ['layout']['xaxis']['range'] = [lower, higher] (same for yaxis)

**Comment by computron** [comment]
In that case I think it's even more interesting to have limits as part of the example. It's a common thing people might want to do so showing them how to do it would be useful

**Comment by computron** [comment]
Can you add the axis limiting code to one of the matminer_examples examples? That is a good place for something that is a little more complex yet nevertheless useful to the user

Close this if the above is already true or if you finish the above

**Comment by ardunn** [comment]
Yep, will do. I working out some of the kinks making a PR to add limits plus fix a few other issues listed here.
