### ISSUE TITLE
AFS should have better presets

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#184]
@dyllamt 

It is asking too much of the user to require them to figure out what functions to use if they just want to try the AFS featurizer. There should be some from_preset("") options that allow the user to get some common functions used without having to read the paper and code up the appropriate lambda functions.

**Comment by dyllamt** [comment]
Presets added in pull request #190.

Maybe similar presets should be added for GRDF, since the user needs to specify bin functions for that too.

**Comment by dyllamt** [comment]
Let me know if you agree with adding presets to GRDF and I'll add them.

**Comment by dyllamt** [comment]
Actually, I just went ahead and added them. Easy addition, although repetitive in the code. If another featurizer used binning functions I would consider making a class for generating the bin functions.

**Comment by computron** [comment]
Thanks!
