### ISSUE TITLE
Clarify LICENSE

### ISSUE THREAD

**Issue by afonari** [hackingmaterials/matminer#185]
Hi,

Is the license MIT?

It is not clear from the LICENSE file.

Thanks,
Alexandr

**Comment by computron** [comment]
Hi Alexandr,

The LICENSE file is a modified BSD (BSD-style) used by Berkeley lab. The chief difference between BSD and MIT is that BSD tries to protect against usage of the Berkeley lab name / brand in promoting products that derive from the code.

To be honest I am not sure what you mean by "clarifying" the license. It is a pretty short license text that explains what you can / cannot do and similar to other BSD licenses. However I will put a note that the open source nature is BSD-style in the updated main docs of matminer.

**Comment by afonari** [comment]
Thanks for the explanation.
