### ISSUE TITLE
new site featurizer: A3, improved angular distribution function

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/matminer#205]
[link to paper](https://aip.scitation.org/doi/pdf/10.1063/1.5020710)

**Comment by dyllamt** [comment]
@ardunn, am I interpreting the distribution function correctly? There are two additional coordinates to the ADF in addition to angle and distance: atomic period and group? So, this is a four-dimensional representation of the site environment that captures angles, distances, and chemistry (group/period).

**Comment by ardunn** [comment]
superseded by #635
