### ISSUE TITLE
Structure featurizers should return equal-length vector of features

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#213]
A condition we would like to maintain for a structure featurizer is that regardless of the number (or order) of sites in the structure, it returns a consistent number and order of features. At the very least, the featurizer should have an *option* (probably default) to operate in this way. Otherwise the featurizer cannot be used as black-box.

The ``GRDF`` and ``AFS`` featurizers were identified as two that do not meet this requirement. The ``CoulombMatrix`` is another.

We explored options such as having ``VectorStats`` (formerly ``PropertyStats``) and ``MatrixStats`` classes that can take n-dimensional arrays of arbitrary dimension (e.g., 1 x 10, 4 x 4, etc) and collapse them to a finite number of features (e.g., trace/N for all N x N matrices). More details in issue #159 .

**Comment by ardunn** [comment]
I would consider the "equal length" versions of `CoulombMatrix` and `SineCoulombMatrix` taken care of by `BagofBonds`. Perhaps we could keep the functionality of these "heterogeneous" featurizers but move them and label them as something other than featurizers?

**Comment by computron** [comment]
Another thing I would like to do:

For a structure with N sites, compute the the fingerprints (of length M) for each site. So now we have an N x M matrix of numbers of the structure.

Personally, I'd like to take the max across the rows (maximum fingerprint value for a single site), which will result in N maximum values for fingerprint. Then I'd like to take the average of those N numbers, yielding a single number for the structure.

Basically, the first step (taking the max of a site fingerprint) corresponds to seeing how "perfect / symmetric" the bonding environment is around a single site. Then, averaging across all sites, you get an average measure of this. For a very ordered / perfect material, this number should be close to 1.0. For a very disordered material, this number will be closer to 0.

But currently there is no way to start with this N x M feature matrix and then reduce it down the way I want.

**Comment by albalu** [comment]
Just FYI: list of structure featurizers that can't be used as black box that I found so far:
CoulombMatrix, SineCoulombMatrix, OrbitalFieldMatrix, MinimumRelativeDistances

**Comment by ardunn** [comment]
these are all fixed  by #634
