### ISSUE TITLE
functionfeaturizer doesn't work with MultipleFeaturizer

### ISSUE THREAD

**Issue by montoyjh** [hackingmaterials/matminer#217]
Because of the column dependence of FunctionFeaturizer (which we solved previously by making feature_labels() None and postprocessing the dataframe in featurize_dataframe), it doesn't play nicely with MultipleFeaturizer.  This seems not ideal, since I'd imagine function featurizer would often be used in a multiplefeaturizer context, but we're going to need to revisit how to flexibly handle feature_labels when feature_labels depend on input columns if we want to fix it.

**Comment by computron** [comment]
@montoyjh should I close this?

**Comment by montoyjh** [comment]
Yep, I believe it's been addressed.
