### ISSUE TITLE
enhancement to FunctionFeaturizer

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#220]
One potential new capability of the FunctionFeaturizer (or derivative of it) would be a ``fit()`` type method that would try a bunch of functions for a single variable and relate it to an output variable. Then, pick the functional form that best correlates with the output as your descriptor.

e.g., I have a descriptor like "avg mass" and want to correlate this with the output "thermal conductivity".

The FunctionFeaturizer would try things like:
- square of avg mass
- exp^(avg_mass)
- exp^(-avg_mass)
- 1/(avg_mass)
- ln(avg_mass)

And in the end, instead of creating a dozen new features, will just retain the one functional form that best correlates with the output. Thus there will only be a single feature for avg_mass (not a dozen), but it might have a different functional form.

**Comment by spacedome** [comment]
In scikit-learn this can be done using the feature_selection module. Feature selection is often integrated into the pipeline as it can depend on the training of the final estimator. Usually in scikit-learn it is part of the pre-processing steps. With methods like feature elimination, it is not known what features are important until after the model is trained. It is also common to do implicit basis expansion (kernel methods) where you get this for free. 

From a ML perspective, it feels like you would only explicitly add a function feature if you had a prior reason for believing it was important. If you were just trying to find better performance through basis expansion, that could be done using scikit-learn as part of the training pipeline, or by using a kernel method. The scikit-learn methods could be integrated here, but is adding this within the scope of matminer?

**Comment by computron** [comment]
This proposal is different than the feature_selection module. One could indeed do the following:

- start with 10 features
- use FunctionFeaturizer to generate 10,000 total features (1000 per initial feature)
- reduce that back down to 10 features using the feature_selection methods in scikit learn

But that's not the proposal. The proposal is:
- Start with 1 of the 10 features
- Generate 1000 features as per before for that 1 feature
- Pick the best function of that 1000
- Repeat for the remaining features

In both cases, you'll end up with 10 features. The first way is less restricted in the way that it can pick features since it can pick two functions of the same feature. Actually, I am trying to avoid that behavior which is the reason for this proposal. It can be argued which is "better". If you really trust your data and feel your feature selection routine is robust, then doing it the first way is fine. But if you just want to find the best "version" of each starting feature, this method is more in-line with that.

>> From a ML perspective, it feels like you would only explicitly add a function feature if you had a prior reason for believing it was important. If you were just trying to find better performance through basis expansion, that could be done using scikit-learn as part of the training pipeline, or by using a kernel method

The kernel methods are limited in what they find. e.g., you do a polynomial kernel and you get all polynomials, but you don't get log or sin functions. Plus, not all ML methods are compatible with kernel methods.

Similarly sklearn has preprocessing like polynomial features but again it doesn't allow for arbitrary mathematical functions

**Comment by computron** [comment]
After reading a little more on feature selection, I don't think this feature is needed. It's probably better just to generate *all* the features using FunctionFeaturizer and then use some standard feature selection strategy or an ML method that incorporates some kind of regularization to reduce down the feature set rather than the method outlined here.
