### ISSUE TITLE
figrecipes should use palettable colors

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#232]
https://jiffyclub.github.io/palettable/

For example, pymatgen DOSPlotter uses this to set color libraries

See also seaborn color palettes:

http://seaborn.pydata.org/tutorial/color_palettes.html

**Comment by ardunn** [comment]
I agree. The colormaps seem to be intended for matplotlib but it doesn't look like there is any reason they wouldn't work with Plotly *crosses fingers*

**Comment by ardunn** [comment]
Upon actually trying this, Paletteable and FigRecipes often really don't play nice together. Mostly because converting matplotlib color maps into Plotly-capable format doesn't work outside of the few examples Plotly provides. Perhaps we could choose one of the better Plotly colormaps to be the FigRecipes default?

**Comment by ardunn** [comment]
@albalu do we have an example of a custom (ie, non-Plotly) colorscale (ie, a list) being used in figrecipes?

**Comment by albalu** [comment]
No we always used one of the pre-defined ones.

**Comment by ardunn** [comment]
@albalu I think for this a good option here to define a function that, given a Paletteable string and a number _n_ of colors to return, returns a list of _n_ "equally spaced" hex colors. Then you can just plug that list into whatever plotlyfig args you want

**Comment by computron** [comment]
You might want to consult with @mkhorton , he is good with colors

**Comment by mkhorton** [comment]
If you want n colors from a qualitative color map, you can do that in Palettable e.g. via:

```
from palettable.colorbrewer.qualitative import Set1_9
colors = Set1_9.colors  # a list of length 9
```

It's tricky to get large palettes that are also color-blind safe however, e.g. see http://mkweb.bcgsc.ca/colorblind/ for some examples of [7 color palettes](http://mkweb.bcgsc.ca/colorblind/img/colorblindness.palettes.trivial.png) and [12 color palettes](http://mkweb.bcgsc.ca/colorblind/img/colorblindness.palettes.simple.png). I don't really think any plot with more than ~7 categorical/qualitative colors will ever look that great though.

>  given a Paletteable string and a number n of colors to return, returns a list of n "equally spaced" hex colors

This is easy enough in Palettable, the `.mpl_colormap` property will return a matplotlib cmap, which then takes values in 0–255 and returns a color, but I wouldn't advise doing this for the above reasons.

But this is just for qualitative/categorical colors. If you need a quantitative, just use viridis courtesy of BIDS :)

**Comment by ardunn** [comment]
@mkhorton Awesome! Thanks

@albalu I think we need to specify exactly what the `colorscale` and `colors` args mean, otherwise this is gonna get very confusing.

**Comment by computron** [comment]
Btw I sometimes use the app "Color Oracle" to get a sense of how a certain color scheme will work (or not work) for color blindness. I'd rate it as something to not prioritize for default color scheme but to have an option to use color blind safe colors

Btw that web page @mkhorton sent out makes me wonder how many traffic accidents are caused by a poor color choice for traffic lights ...

**Comment by mkhorton** [comment]
https://link.springer.com/chapter/10.1007/978-94-011-5408-6_54

[xScope](https://xscopeapp.com) is a really nice app for simulating color blindness too, though I don't have a copy of the latest version sadly

**Comment by computron** [comment]
I think @utf did a good job of colors on the various codes like "sumo", etc. Might be worth it to just have a discussion w/him for the Figrecipes overall graphic design - colors, fonts, font sizes, etc.
