### ISSUE TITLE
width for docs is too small

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#234]
Can we make it 25% bigger?

![screen shot 2018-05-25 at 1 33 38 pm](https://user-images.githubusercontent.com/986759/40565163-4d421e7e-6020-11e8-955c-467ba7a9a4b4.png)

**Comment by computron** [comment]
(this would be max_width being 25% bigger)

**Comment by ardunn** [comment]
Just added a commit which sets the max width to 1000px (it was 800px before)

For reference, max-width in docs_rst/nature.css needed to be added for div.body
