### ISSUE TITLE
partial DOS featurizer

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#240]
A DOS featurizer that is a 16-element vector of the various s, p, d, f overlaps

i.e., s-s interaction is the square of the s-projected DOS, s-p interaction is the multiplication of the s projected and p-projected DOS, etc

Then, integrate the value of each of these interactions either to fixed energy cutoff (Max Dylla way) or using Fermi energy smearing (AJ way) to produce a single number for each of the 16 interactions.

**Comment by albalu** [comment]
We discussed this yesterday with Max. I will take care of it via BandEdge dos featurizer which optionally returns:

1) cbm_ vbm_ s, p, d, f
2) cbm_ vbm_ sp, sd, sf, pd, pf, df
3) cbm_Pb_s, cbm_Pb_p, ... vbm_Pb_s, .... where Pb is optionally set as one of the species in species=[str] input arg

the energy_cutoff can be set to a fixed number in class instantiation or a variable featurize arg (optional) that if it's set, it would override the class energy_cutoff (e.g. the fermi calculated at 1e20 via DopingFermi for each compound).

**Comment by computron** [comment]
Ok - note that the "Fermi energy smearing" is basically a smooth cutoff rather than a hard cutoff, see the paper:

https://www.cambridge.org/core/journals/journal-of-materials-research/article/new-opportunities-for-materials-informatics-resources-and-data-mining-techniques-for-uncovering-hidden-relationships/EF98DD1402C43B3B683F603284C0AD62

**Comment by albalu** [comment]
This should be addressed via #244 . The smearing is always done with the default bandwidth of 0.1 eV

**Comment by computron** [comment]
Ok but the smearing I am talking about is different.

I think you and Max both design metrics that are "hard" - i.e., a hard cutoff of how deep into the bands to go or an integer number for the number of significant contributors with a "hard" cutoff on what is considered significant. I tend to design and prefer metrics that are smooth and continuous.

For example, to see how deep into the bands to go, the paper above shows how to do so continuously / gracefully (not just smearing the dos and giving a hard cutoff afterward) where the energies that are closest to the band edge are weighted the most and energies further from the band edge are weighted less in a continuous manner. Similarly, for the number of significant contributors, it would be better to define some kind of entropy metric (e.g., sum of xln(x) over all orbital contributions or something) rather than an integer based on setting some hard threshold for what's "significant".

I'll add a new issue regarding some of the smoothness factors.
