### ISSUE TITLE
qlaunch -m doesn't work on slurm sometimes

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/matminer#243]
Both @albalu and I have this problem on cori, qlaunch is just unable to get the number of jobs in the queue. You can get this info on shell via squeue, so there shouldn't be any reason FWs can't get the number of jobs in the queue

**If there is existing workaround issue/tracker for this, pls close this issue

**Comment by computron** [comment]
Someone needs to look into the function:

fireworks.user_objects.queue_adapters.common_adapter.CommonAdapter#get_njobs_in_queue

For SLURM, it is using "squeue" as the queue status command (perhaps with additional flags for username, etc). You'll need to see what's going wrong in:

fireworks.user_objects.queue_adapters.common_adapter.CommonAdapter#_parse_njobs

In particular for SLURM it's using:

```
        if self.q_type == 'SLURM':
            # subtract one due to trailing '\n' and split behavior
            return len(output_str.split('\n'))-1
```

**Comment by computron** [comment]
Looking at this with @ardunn , it looks like his ``queue`` field in ``my_adapter`` is strange in that it also has a ``-C cori,knl,etc...``` tag as part of it.

**Comment by computron** [comment]
Fixed by moving the "#SBATCH -C blah,blah" options to ``pre_rocket`` section of my_qadapter.yaml
