### ISSUE TITLE
PlotlyFig heatmap, triangle, violin, and bar don't work with hover* options

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/matminer#255]
Particularly, hoverinfo does not work in any of these. It displays the default hoverinfo regardless of the plotlyfig hoverinfo value. Hovermode has the same problem.

**Comment by computron** [comment]
What would you expect the hoverinfo to be able to show for these kinds of plots? Unlike the scatter plot, each "point" to hover over is not a single material.

**Comment by ardunn** [comment]
- On a bar plot, you might only want to show the y value, not the x.
![bar](https://user-images.githubusercontent.com/19936203/41428592-68b1d876-6fbf-11e8-9994-276ae29f2521.png)
- On a heatmap, you might only want to show z, not x and y 
![heat](https://user-images.githubusercontent.com/19936203/41428774-eeb0afba-6fbf-11e8-9ac2-b9c881483454.png)
- In the ternary plot, it might be useful to identify what each of the samples is by name, instead of just the A/B/C
![tri](https://user-images.githubusercontent.com/19936203/41429150-11bc88de-6fc1-11e8-97ea-aeeeecbb1f03.png)

Thinking about it though, for violin there is not really a good use for hoverinfo.

**Comment by computron** [comment]
* The ternary plot I think you definitely want to know the point
* The bar plot - the y value would be nice to have
* Heatmap - doesn't seem so important to only show z
* Violin - not much use as you said

**Comment by albalu** [comment]
Ternary plot supports labels just like xy. We can rename if it's not intuitive but you just need to set labels = ['mpid', 'formula'] or labels='formula'; we can either override hoverinfo input or just throw an error if it was set and say set the labels instead?

**Comment by ardunn** [comment]
@albalu the issue is that you may not want to display the x/y/z coordinates in ternary while using custom labels. 

I think this issue can be solved for any plotly plot by just passing hoverinfo=self.hoverinfo into the plotting function (eg. `go.Bar`) **or** setting a key in the layout.
