### ISSUE TITLE
integrate AMP descriptors into matminer

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#256]
It would be great if the site descriptors included in the AMP library:

https://amp.readthedocs.io/en/latest/

could be integrated with atomate.

It would require the user to install AMP, but there would be some adapter to compute the AMP-supported fingerprints with matminer.

**Comment by kjappelbaum** [comment]
Amp stores it's fingerprint in a file-based database for re-usage (which could also be interesting for matminer), so one would need to figure out how one wants to handle this. I used something like this in the past, which is of course not highly-optimized since amp usually likes ase trajectories:
 
```
def get_fingerprint_from_structures(structure,
                                    output_dir=None,
                                    type=None,
                                    cutoff=10.0,
                                    nmax=5,
                                    gs=None):
    """
    Function creates AMP fingerprint structures.
    
    Args:
        structure (object): ase structure object
        output_dir (str): Path to db directory
        type (str): Fingerprint name as string, available are the ones implemented in AMP,
            i.e. Gaussian, Zernike and Bispectrum
        cutoff (float): Cutoff for fingerprint
        nmax (int): polynomial order
        gs (dict): coefficients of atomic density function (for Zernike).

    Returns:

    """

    if type == 'Gaussian':
        logger.debug('Will use Gaussian fingerprint')
        descriptor = Gaussian(dblabel=output_dir, cutoff=cutoff, Gs=gs)
    elif type == 'Zernike':
        logger.debug('Will use Zernike fingerprint')
        descriptor = Zernike(
            dblabel=output_dir, cutoff=cutoff, nmax=nmax, Gs=gs)
    elif type == 'Bispectrum':
        logger.debug('Will use Bispectrum fingerprint')
        descriptor = Bispectrum(
            dblabel=output_dir, cutoff=cutoff, nmax=nmax, Gs=gs)
    else:
        logger.error(
            'Could not find your fingerprint specification, wiil now use Zernike'
        )
        descriptor = Zernike(
            dblabel=output_dir, cutoff=cutoff, nmax=nmax, Gs=gs)

    image = [read(structure)]
    image = hash_images(image)
    descriptor.calculate_fingerprints(image)

    return descriptor.fingerprints[list(image.keys())[0]]
```

**Comment by WardLT** [comment]
It seems like we could easily port this code into a matminer featurizer, which might also close issue #282 (bispectrum coefficients) as well.

@kjappelbaum , would you mind going into a little detail about the benefits of the database backing in Amp?

**Comment by kjappelbaum** [comment]
The database is useful to avoid re-calculation of a fingerprint. Amp will create two folders, one for neighborlists and one for the fingerprints and will hash each structure and create a file with the hash as filename. In case you start training, AMP will check the database if the fingerprint/neighborlist already exists and only recalculate if needed. In case you do not want this in matminer, one could think about writing to /dev/null or simply deleting the folders afterwards. 

In AMP this is especially useful since you feed the training function with ase trajectories (and not the fingerprints) and the fingerprint type (as string) and in this way AMP can avoid redundant calculations if you do e.g. hyperparameter tuning.

**Comment by kjappelbaum** [comment]
I am not sure about what a good API design would be. Would you prefer an AMP featurizer that takes the fingerprint type as argument or would you create a separate featurizer for each fingerprint type and put then all of them into a amp.py file. I would probably prefer this, combined with the cross importing as discussed in` https://github.com/hackingmaterials/matminer/issues/378`. If you agree with that, I would move forward with implementing a clean version.

**Comment by WardLT** [comment]
I like the idea of separate featurizers for each type of fingerprint to reduce the complexity of options passed to the featurizer. I am presuming each of the different fingerprint types have additional options that could be specified beyond the cutoff. Is that right? If not, maybe a single class would be sufficiently simple.

A good route to multiple classes could be to make a `BaseAMPFeaturizer` class that holds the main logic for interacting with AMP and then subclass it for each kind of fingerprint. 

Regarding the previous discussion about databases: I'm in favor of avoiding use of the database or, at least, keeping its use transparent. The current approach in matminer is to have a dataframe as the ground truth for the featurization and my concern is that the database could confuse users if it is also a route for storing the features. Additionally, is it possible to turn off the database for speed and applications where disk access is limited (e.g., when building a web service with matminer)?

**Comment by kjappelbaum** [comment]
I currently do not really see a way around the database without changes in AMP itself (there is no switch for turning the db of in the API). I started working on the AMP classes (as you suggested, I use a BaseAMPFeaturizer and subclass it), in which I delete the database directly after featurization, and will open a PR in which we can discuss the draft in the upcoming days.

**Comment by ardunn** [comment]
superseded by #635
