### ISSUE TITLE
NIST JARVIS dataset as a matminer example data set

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#261]
Recently Kamal Choudhary et al published some good ML results based on mining the JARVIS database:

https://arxiv.org/abs/1805.07325

It would be great if that data set can be available on matminer so others can try their ML algorithms. I asked Kamal about how to do this and he referred me to this code:

https://github.com/usnistgov/jarvis/blob/master/jarvis/db/static/explore_db.py

It seems like all the info needed to make the dataset available on matminer as an example is there. If the file is big, we may want to have a separate repo for large datasets so the matminer repo doesn't become bloated with datasets.

Separately, Kamal has discussed adding his descriptors to matminer. But for now, just having the data set would already be interesting.

**Comment by WardLT** [comment]
We have indexed JARVIS in the Materials Data Facility, and I made an example for using our index. I ported that example to use matminer's data retrieval class. Should I add this to the example repository?
[jarvis-example.pdf](https://github.com/hackingmaterials/matminer/files/2138425/jarvis-example.pdf)

I still have a little bit of work to do to make it easier to access the crystal structures, which would allow for machine learning.

**Comment by computron** [comment]
I do think you should add the example to matminer_examples

That said, it would be nice to have just a single function call to get both the crystal structures and the data for the referenced arxiv paper like the other methods without having to issue Forge queries, etc. So that the data is there like the other test datasets with a single Python function call -> pandas dataframe.

**Comment by WardLT** [comment]
Sure, I'll go ahead and add it to matminer_examples. 

I certainly agree, issuing multiple queries to get the structures would be tedious and presents an unneeded learning curve. We're still figuring out best to approach that problem.

**Comment by ardunn** [comment]
@computron considering we have a majority of the JARVIS database in our Figshare datasets, as well as the MDF Forge JARVIS access, can we consider this issue closed?

**Comment by ardunn** [comment]
This issue is closed, JARVIS DFT3D and 2D and the exact training dataset Choudhary et al. used are already in matminer, see matminer dataset summary page
