### ISSUE TITLE
Failures in Voronoi Tessellations

### ISSUE THREAD

**Issue by WardLT** [hackingmaterials/matminer#266]
The Voronoi-tessellation-based featurizers all have a minor error rate due to problematic structures failing to tessellate.

As an example, `mp-623782` fails to tessellate due to an error running qhull. 

There are a few possible routes we could take to trying to lower the error rate:
1. Making sure our cutoff for Voronoi tessellations is large enough to capture all NNs
2. Perturbing the unit cell and re-attempting the tessellation (suggestion from Bryce Meredig).

If these don't work, we should at least report actionable error messages (e.g., "tessellation failed, consider removing this entry from the dataset or turning on `ignore_errors`)

**Comment by computron** [comment]
I just created a PR in the VoronoiNN class in pymatgen to fix the cutoff issue:

https://github.com/materialsproject/pymatgen/pull/1193

When merged, this should fix problems for some structures but I don't think it will fix mp-623782. I tried perturbing mp-623782 but that didn't seem to fix the problem, so I didn't implement that strategy. There might be something more fundamental going on in either qhull or the pymatgen wrapper causing the problem.

**Comment by computron** [comment]
I also just pushed a commit to help guide users to setting ignore_errors=T:

483bdaf75678b01c12e2d8cc66a710a902dcbd04

**Comment by utf** [comment]
Hopefully this should be fixed by materialsproject/pymatgen#1289.

**Comment by computron** [comment]
I am going to close this for now as I think we've solved it as much as we plan to at the moment. If someone sees this re-appearing please feel free to re-open.
