### ISSUE TITLE
matminer CircileCI test environment

### ISSUE THREAD

**Issue by albalu** [hackingmaterials/matminer#270]
With the current test config file that uses tox, the python virtual environment is not used after installation. See this line in the test result:
"
pyenv doesn't seem to be installed, you probably don't want this plugin installed either.
py36 installdeps: nose==1.3.7, coverage==4.4.1, coveralls==1.1, -r/home/circleci/matminer/requirements.txt
"
So the requirements get installed twice which is inefficient and makes it difficult to implement requirements-optional. Not sure how to resolve it, I got around this issue in AMSET by running the test w/o tox: 
https://github.com/hackingmaterials/amset/blob/master/.circleci/config.yml

**Comment by ardunn** [comment]
Thanks for bringing this up. Tbh I had not put much thought into problems with venv/tox/etc because this testing config is basically copied from the fireworks config, and at first it seemed to "just work"

Is the issue specifically that the optional requirements are not installed by the test suite?

**Comment by albalu** [comment]
The issue is that the first part (setup) is basically ignored and when
running the tests requirements are installed again as if you never created
a venv.
