### ISSUE TITLE
Have progress bar during featurization

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/matminer#273]
It might be nice to have a progress bar (which could be turned on/off) during featurization, so you'd have an idea of how long a featurizer will run. `tqdm` seems like a good package to do this

**Comment by computron** [comment]
Agree, we use tqdm to do progress bars for some of the data retrieval already

**Comment by computron** [comment]
Also I guess this will mainly be for featurize_many?

**Comment by ardunn** [comment]
Yeah I imagine featurize_many is the lowest level at which the progress bar would be present. Although it would be good if it worked with the higher level methods (featurize_dataframe, fit_featurize_dataframe, MultiFeaturizer.featurize_dataframe, MultiFeaturizer.fit_featurize_dataframe)

**Comment by computron** [comment]
Sure, I think we are on the same page here

**Comment by ardunn** [comment]
closed via #275
