### ISSUE TITLE
add Jarvis data set to matminer sample data sets

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#279]
Not sure if we should be moving larger sample data sets to another package, or coding a way to download the raw data file in JSON on-demand

https://github.com/usnistgov/jarvis/blob/master/jarvis/db/static/jarvis_ml-train.ipynb

**Comment by ardunn** [comment]
@computron considering we have a majority of the JARVIS database in our Figshare datasets, as well as the MDF Forge JARVIS access, can we consider this issue closed?

**Comment by computron** [comment]
yes please close
