### ISSUE TITLE
add Jarvis descriptors to matminer

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#280]
See: 

https://github.com/usnistgov/jarvis/blob/master/jarvis/sklearn/get_desc.py

**Comment by computron** [comment]
See also:

https://github.com/usnistgov/jarvis/blob/master/jarvis/db/static/jarvis_ml-train.ipynb

Kamal Choudhary has (friendly) dared people to try to beat the results...

**Comment by ardunn** [comment]
this is done
