### ISSUE TITLE
SOAP descriptors

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#284]
We might be able to add SOAP descriptors through:

https://github.com/SINGROUP/SOAPLite

It might be a little wonky compared to a native implementation
- need to convert structure to ASE (pymatgen can do this, not so bad)
- installation requires C compilation (they have a precompiled C library for linux, not sure how well this will work)

But at least there is a relatively quick(?) way to make it an option for people - if they install SOAPlite they can get SOAP descriptors

**Comment by ardunn** [comment]
closed via #370
