### ISSUE TITLE
Problems with parallel featurization and FunctionFeaturizer

### ISSUE THREAD

**Issue by WardLT** [hackingmaterials/matminer#295]
Running `featurize_dataframe` for FunctionFeaturizer yields wrong results when running in parallel. The example code below yields a different for each featurization for the current version of matminer.

I have confirmed this result on Python 3.6 on Windows, and a user has also found it to occur on Python 3.7.

```python
ff = FunctionFeaturizer()
d = pd.DataFrame({'t2': [1, 2, 3]})

ff.fit(d)

print(ff)

ff.set_n_jobs(1)
print(ff.featurize_dataframe(d, ['t2']))

ff.set_n_jobs(2)
d.drop(ff.feature_labels(), 'columns', inplace=True)
print(ff.featurize_dataframe(d, ['t2']))
```

**Comment by computron** [comment]
@montoyjh any thoughts on this?

**Comment by montoyjh** [comment]
Will take a look.

**Comment by ardunn** [comment]
This may be from when I removed the override of featurize_dataframe from FunctionFeaturizer via  022846cfe2593127ede5a308b67c4171feffa7fc

It did not fail any tests at the time though...

**Comment by montoyjh** [comment]
@WardLT can you post the output of your test?  I'm getting two dataframes that are the same other than the np.nan entry (on py3.6/OSX 10.11).

**Comment by WardLT** [comment]
Sure, the output from my Windows machine is below.

In case it helps: One thought I had about why this error could occur is that something changes while pickling and unplicking the object when transmitting it to the worker thread. That's not the case. I ran a check where I cloned the featurizer by pickling and unpickling it, and the clone gives the correct results.

Let me know if there are any other tests I can run for you.

-----

```
FunctionFeaturizer(combo_function=<function prod at 0x0000015F0660C2F0>,
          expressions=['x', '1/x', 'sqrt(x)', '1/sqrt(x)', 'x**2', 'x**-2', 'x**3', 'x**-3', 'log(x)', '1/log(x)', 'exp(x)', 'exp(-x)'],
          latexify_labels=False, multi_feature_depth=1,
          postprocess=<class 'float'>)
FunctionFeaturizer: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 73.20it/s]
   t2  sqrt(t2)  t2**(-3)  t2**3  exp(-t2)   log(t2)  t2**2  1/log(t2)  \
0   1  1.000000  1.000000    1.0  0.367879  0.000000    1.0        NaN
1   2  1.414214  0.125000    8.0  0.135335  0.693147    4.0   1.442695
2   3  1.732051  0.037037   27.0  0.049787  1.098612    9.0   0.910239

     exp(t2)  1/sqrt(t2)  t2**(-2)      1/t2
0   2.718282    1.000000  1.000000  1.000000
1   7.389056    0.707107  0.250000  0.500000
2  20.085537    0.577350  0.111111  0.333333
FunctionFeaturizer: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 46.11it/s]
C:\Users\Logan\Miniconda3\lib\site-packages\plotly\tools.py:103: UserWarning:

Looks like you don't have 'read-write' permission to your 'home' ('~') directory or to our '~/.plotly' directory. That means plotly's python api can't setup local configuration files. No problem though! You'll just have to sign-in using 'plotly.plotly.sign_in()'. For help with that: 'help(plotly.plotly.sign_in)'.
Questions? Visit https://support.plot.ly

   t2  sqrt(t2)  t2**(-3)     t2**3   exp(-t2)  log(t2)     t2**2  1/log(t2)  \
0   1     1.000  1.000000  1.000000   2.718282     1.00       NaN   0.000000
1   2     0.125  8.000000  0.693147   0.500000     0.25  1.414214   1.442695
2   3     9.000  0.333333  0.111111  20.085537    27.00  0.910239   1.098612

    exp(t2)  1/sqrt(t2)  t2**(-2)      1/t2
0  1.000000    1.000000  1.000000  0.367879
1  0.707107    7.389056  4.000000  0.135335
2  0.577350    1.732051  0.037037  0.049787
```

**Comment by montoyjh** [comment]
Upon inspection of your output, @WardLT, it kind of looks like each rows contains the right set of numbers, but that they're just not assigned to the correct row.  What happens if you re-fit the featurizer after the drop command?

**Comment by montoyjh** [comment]
Actually, in @ardunn's linked commit, the unittests were revised such that they don't explicitly test `featurize_dataframe` any more independently of fitting.  So presumably the user should always use `fit_featurize_dataframe`.

**Comment by WardLT** [comment]
Refitting does not seem to fix the problem. Nor does calling `fit_featurize_dataframe`

And, after running this a few times, the output that the parallel `featurize_dataframe` returns changes each time. Not sure if that adds any helpful clue.

**Comment by montoyjh** [comment]
Yeah my guess is there's something that is implicitly ordered on some systems that's being scrambled.  I'll check it out on my wondows machine once i can get to it.

**Comment by montoyjh** [comment]
@WardLT still haven't gotten to testing on windows, but based on the output you shared, have a hunch it might be fixed here.  Mind trying the test with this branch?

https://github.com/montoyjh/MatMiner/tree/function_featurize

**Comment by montoyjh** [comment]
Okay, I just tested on windows, and was able to reproduce the bug and fix it in the aforementioned branch.  I'm glad it gets triggered on Windows, because it's a more general bug, and I'm really not sure why it's particular to OS (my guess is set ordering-reordering happens in a different way on Windows?).  I'll go ahead and issue the PR.

**Comment by WardLT** [comment]
Great! I was able to verify that the fix works on my machine too. Thanks, @montoyjh !
