### ISSUE TITLE
Provide Flat Outputs for All Structure Featurizers

### ISSUE THREAD

**Issue by WardLT** [hackingmaterials/matminer#300]
Most machine learning libraries work best with 1D, "flat" features. Several of our current structure featurizers return 2D matrices or dictionaries rather than a 1D vector. We should modify these classes to provide the ability to output 1D features, if desired (see PR #299 as an example).

The relevant classes are:

- [x] CoulombMatrix
- [x] SineCoulombMatrix
- [ ] MinimumRelativeDifferences 
- [ ] RadialDistributionFunction 
- [ ] ElectronicRadialDistributionFunction 

For the two CoulombMatrix classes, we should flatten the outputs by computing eigenvalues and then padding the eigenvalues with zeros to make all outputs the same length. This is a standard practice when using CMs, where the length of vectors is chosen to be the maximum number of atoms in the unit cell for the training set. We should probably add a fitting routine to determine the maximum atom count.

**Comment by ardunn** [comment]
@WardLT what do you think is the best way to flatten the *RDF outputs?
