### ISSUE TITLE
structure_to_oxidstructure should be parallelised 

### ISSUE THREAD

**Issue by utf** [hackingmaterials/matminer#302]
The `matminer.utils.conversions.structure_to_oxidstructure` function takes a very long time when processing many structures. Currently the implementation runs only on a single thread. A quick and easy way to improve performance would be to introduce an `n_jobs` argument that enables parallelisation. Similar to the behavior of `n_jobs` in scikit-learn, providing `n_jobs=-1` would set the number of jobs equal to the number of processors.

**Comment by computron** [comment]
The easiest way to do this would probably to make this into a featurizer, which would automatically support parallelism. Similar for some of the other conversion functions

e.g. we can have a module of "conversion" (or other name) featurizers that do these kinds of transformations, the only thing is that the "in_place" option would probably no longer be supported.

**Comment by computron** [comment]
(It would also allow using these conversion tools as part of a Pipeline)

**Comment by utf** [comment]
Seems like a nice idea. Naively, looking through the list of functions in `matminer.utils.conversions`, it looks like every function in there *could* be converted into a featurizer. If anyone has any objections as to why this might be a bad idea I'd like to hear their thoughts. Otherwise, I'll go ahead and refactor them all.

**Comment by WardLT** [comment]
I support making all of these based on the Featurizer API. Is the idea to keep in the `utils.conversions` module?

**Comment by WardLT** [comment]
:+1: I think it's reasonable to put them in a special module under `featurizers.conversions`, as long we document clearly that they do not produce ML-ready features but are instead utilities.

**Comment by computron** [comment]
I think you can just call it ``{}_object``

I would say it shouldn't overwrite anything in the dataframe by default, that should be optional if there at all
