### ISSUE TITLE
Test files could use updated to fix deprecations/user warnings

### ISSUE THREAD

**Issue by Doppe1g4nger** [hackingmaterials/matminer#313]
I've noticed that there are quite a few deprecations and warnings raised when running the tests on CircleCI. The deprecation issues should be fairly easy to fix but some of the user warnings may be more involved to address. Some of the deprecations warned of total removal in December 2018 so they should be addressed soonish and the rest might as well be looked at at the same time.

**Comment by computron** [comment]
@Doppe1g4nger can you give this a go and let me know which ones you don't know how to solve?

The total removal ones should relate to conversions being a featurizer, perhaps @utf can help w/that one

**Comment by utf** [comment]
Is this now fixed by #320 ?

**Comment by Doppe1g4nger** [comment]
More or less, the remaining deprecation warnings come from tests on the deprecated converters and will presumably be removed when the converters are. The warnings for using np.matrix should probably just be ignored, numpy doesn't seem to have a plan to remove the matrix object anytime soon. There were a few other misc. ones that stuck around but I couldn't find their source and they all seemed very minor.

**Comment by computron** [comment]
@Doppe1g4nger I would suggest to either close the issue or list out the remaining warnings to fix before considering the issue closed

**Comment by Doppe1g4nger** [comment]
The remaining issues are either very minor or should be fixed once the deprecated functions are removed. Closing this.
