### ISSUE TITLE
Transition existing datasets to JSON

### ISSUE THREAD

**Issue by Doppe1g4nger** [hackingmaterials/matminer#315]
I'm currently working on transitioning the existing matminer datasets over to json. I successfully converted them all using @utf 's utility and confirmed that the dataframes when loading these json files are identical to the ones produced by the current load_dataset() function. 

I uploaded the dielectric_constant dataset json file to figshare (see here: https://figshare.com/articles/Dielectric_Constant_Data/7108790) and it appears I can have an individual download for either the csv or the json.gz in addition to a download of them bundled together. 

Therefore I see no need to remove the csv files from the figshare itself if we want to keep them available. The question now is do we keep the csv files available as a download source in matminer or should we keep it consistently json files? 

It seems to me that there are more negatives to keeping csv as an option than positives as there are issues with the encoding of certain objects, we then have to maintain metadata for them both, and it's only a single line of code for a user to just convert the dataframe to a csv themself.

**Comment by ardunn** [comment]
imo we should only keep json

probably need @computron approval tho

**Comment by computron** [comment]
Sounds good to me

**Comment by Doppe1g4nger** [comment]
Closed by #316
