### ISSUE TITLE
Rework CircleCI configuration

### ISSUE THREAD

**Issue by Doppe1g4nger** [hackingmaterials/matminer#330]
In setting up datasets and their testing in #328 it became apparent that it would be useful to have tests that run on a set schedule rather than during every commit (e.g. testing that datasets can be downloaded from the Figshare repository). This can be done using the CircleCI Workflows functionality: https://circleci.com/docs/2.0/workflows/ by scheduling a workflow to run on a cron job.  While this is being tackled #270 can probably be addressed as well.

**Comment by computron** [comment]
Are there "quick" tests that can be run quickly and on every commit? e.g., making sure that the resource exists on Figshare at all (without necessarily verifying its contents).

**Comment by Doppe1g4nger** [comment]
Hmm, I _could_ change the tests to just ping the download link and make sure it gets back a valid response. This wouldn't ensure the data integrity but it would make sure the download link is active. I like the idea of changing the current tests to do this on every commit, but I still think some sort of more comprehensive test like the current ones should be set up to run on a ~weekly basis.

**Comment by Doppe1g4nger** [comment]
Some other potential improvements to the test process have become apparent so I'm generalizing this Issue to better encompass what really needs done.

- [ ] Implement Workflows to have a scheduled test against datasets and a shorter test against PRs.
- [ ] Make tests run against install created with setup script rather than direct repo code

**Comment by ardunn** [comment]
> Some other potential improvements to the test process have become apparent so I'm generalizing this Issue to better encompass what really needs done.
> 
>     * [ ]  Implement Workflows to have a scheduled test against datasets and a shorter test against PRs.
> 
>     * [ ]  Make tests run against install created with setup script rather than direct repo code

First one is done, second one doesn't seem like it is something which is typically done in python development.
