### ISSUE TITLE
Propnet descriptors in matminer

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#335]
I think we are getting to the point where propnet descriptors should be integrated into matminer:

https://github.com/materialsintelligence/propnet

* Propnet is starting to be relatively mature
* We are already doing integrated matminer-propnet tests to see if propnet will accelerate data mining
* There are papers coming out that could really benefit from propnet features, e.g. see:

https://arxiv.org/abs/1811.06219

**Comment by ardunn** [comment]
superseded by #335
