### ISSUE TITLE
add text-mined element embeddings to matminer via ElementProperty

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#343]
It would be nice to have text-mined element embeddings in matminer. A whole separate study might compare these against MAGPIE-style descriptors.

The general strategy would be:

* Add the raw embedding data to matminer.utils.data_files
* Implement the embedding data in matminer.utils.data as a subclass of the AbstractData object
* Implement the embedding featurize as a preset value in ElementProperty Featurizer in matminer.featurizers.composition. Once you have the embeddings as "AbstractData" above this step should be simple.

@ardunn can you work with Leigh on this?

**Comment by ardunn** [comment]
Sure, what would you think about also adding a separate (but related) festurizer for the word embeddings of entire materials? leigh mentioned he could also give the embeddings for all materials, so this featurizer would just return the word embedding for a formula and would throw an error if the formula was not found/known

**Comment by ardunn** [comment]
this is done
