### ISSUE TITLE
Add U-apI descriptors to matminer

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#344]
Will require the user to install ABCNN code. See:

https://gitlab.com/ankitjainmeiitk/abcnn/blob/master/example/FP.py

for an example of usage. Note that in the example, the "energy" part is the output value so it should not be included in the fingerprint.

**Comment by computron** [comment]
Can we do this one relatively quickly

@utf might have been working with this one already, so maybe it can go quickly

**Comment by ardunn** [comment]
https://journals.aps.org/prb/abstract/10.1103/PhysRevB.98.214112

Posting here for reference

@computron were you thinking to make our own implementation or just using theirs?

**Comment by ardunn** [comment]
superseded by #635
