### ISSUE TITLE
fix plotly tests

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#348]
in particular matminer.figrecipes.tests.test_plots.PlotlyFigTest#test_violin

Note that I modified this to pass simply by skipping the test. So remove the skip decorator first, then get it to pass CircleCI

**Comment by computron** [comment]
note that @Doppe1g4nger might have changed the test from the original version, not sure if that helps or hurts things

**Comment by ardunn** [comment]
@computron Should not be a problem (fingers crossed)
