### ISSUE TITLE
get_pymatgen_descriptor not available

### ISSUE THREAD

**Issue by ldeecke** [hackingmaterials/matminer#35]
A very interesting project. However when I follow the tutorial and try to:

```python
from matminer.descriptors.composition_features import get_pymatgen_descriptor
avg_mass = np.mean(get_pymatgen_descriptor('LiFePO4', 'atomic_mass'))
    ...
```

this yields a`ModuleNotFoundError: No module named 'matminer.descriptors'` under v0.1.1.

Am I missing something?

**Comment by computron** [comment]
Hi,

1 - can you post on:
https://groups.google.com/forum/#!forum/matminer

We use the Github more for internal development.

2 - we refactored a lot of matminer recently so the imports and functions changed. For example, the pymatgen_descriptor is under the featurizers package and under a class stucture. I'll need to revise the notebooks, hopefully sometime this week, to reflect the new code.

**Comment by ldeecke** [comment]
Thanks for your comment, looking forward to those updates then --

**Comment by computron** [comment]
@ldeecke I just pushed some updates so that the notebooks should work now

Please keep in mind that a lot of matminer is under construction, so examples might get out of sync for the next month or so. Hopefully after that things will start to stabilize.

**Comment by ldeecke** [comment]
Good to hear, looking forward to those updates.
