### ISSUE TITLE
Cannot import pip-installed version of matminer, syntax error related to `SiteStatsFingerprint`

### ISSUE THREAD

**Issue by mkhorton** [hackingmaterials/matminer#355]
Seems like a problem with the `async=True` portion causing a syntax error and the whole module failing to import (if you remove `async=True` it imports fine).

```
from robocrys import StructureCondenser, StructureDescriber
  File "/Users/work/.venv/mp-dash-components/lib/python3.7/site-packages/robocrys/__init__.py", line 2, in <module>
    from robocrys.condense.structure import StructureCondenser
  File "/Users/work/.venv/mp-dash-components/lib/python3.7/site-packages/robocrys/condense/structure.py", line 13, in <module>
    from robocrys.condense.component import (get_sym_inequiv_components,
  File "/Users/work/.venv/mp-dash-components/lib/python3.7/site-packages/robocrys/condense/component.py", line 18, in <module>
    from robocrys.condense.fingerprint import get_structure_fingerprint
  File "/Users/work/.venv/mp-dash-components/lib/python3.7/site-packages/robocrys/condense/fingerprint.py", line 5, in <module>
    from matminer.featurizers.structure import SiteStatsFingerprint
  File "/Users/work/.venv/mp-dash-components/lib/python3.7/site-packages/matminer/featurizers/structure.py", line 2523
    atom_fea = Variable(input_[0].cuda(async=True), volatile=True)
```

**Comment by mkhorton** [comment]
Note that I think this is only a `SyntaxError` on Python 3.7+ which is why I think your CI is still working, even though the pip install is broken.

**Comment by WardLT** [comment]
Does it given any indication of what is wrong about the syntax? I'm not familiar enough with 3.7 to know why this statement isn't valid.

**Comment by mkhorton** [comment]
`async=True` is redefining a builtin, I believe. "async" shouldn't be used as a kwarg. I don't use async myself to know though, all I know is that if I delete that part it imports fine.

**Comment by WardLT** [comment]
Oh! Yes, this problem has some layers. `aync` has been renamed into `non_blocking` in newer versions of pytorch, which should get around the problem.

Not sure if CGCNN is compatible with newer versions of pytorch. Hopefully, we have some unittests to check it

**Comment by WardLT** [comment]
Thanks for pointing out the 3.7 connection to this bug. Maybe we should start including Python 3.7 in the unittests.

**Comment by mkhorton** [comment]
No problem, I just spotted it in the 3.7 changelog:

>Backwards incompatible syntax changes:
>* async and await are now reserved keywords.

We're deploying a web app on our end + trying to use 3.7 as a base image, I don't have 3.7 set up myself in any CI yet though so also probably should do that :)

**Comment by mkhorton** [comment]
It's a bit of a hack, but if CGCNN wasn't compatible with the new pytorch, you could also just pass in the kwarg as `**{'async':True}`, it'd obviously still not work in 3.7, but it would import fine, and as far as I can see that code block is only evaluated if you have CUDA enabled anyway.

**Comment by WardLT** [comment]
Thanks for the suggestion!
