### ISSUE TITLE
Caching test fails unittest test suite

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/matminer#364]
For whatever reason, test_caching of multifeaturizer fails the test suite now that we transitioned to unittests from old (deprecated) nose. 

What is strange is that the test seems to pass locally by using `python test_base.py` (i.e., running `unittest.main()`). 

Locally, running `python setup.py test` fails with:
```bash
======================================================================
FAIL: test_caching (matminer.featurizers.tests.test_base.TestBaseClass)
Test whether MultiFeaturizer properly caches
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ardunn/alex/lbl/projects/common_env/dev_codes/matminer/matminer/matminer/featurizers/tests/test_base.py", line 416, in test_caching
    self.assertEqual(2, _get_all_nearest_neighbors.cache_info().hits)
AssertionError: 2 != 15
----------------------------------------------------------------------
```

On circleCI though, the test has this similar failure:

```bash
======================================================================
FAIL: test_caching (matminer.featurizers.tests.test_base.TestBaseClass)
Test whether MultiFeaturizer properly caches
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/matminer/matminer/featurizers/tests/test_base.py", line 416, in test_caching
    self.assertEqual(2, _get_all_nearest_neighbors.cache_info().hits)
AssertionError: 2 != 8
```

So the problem only seems to happen when running all the tests. 

Perhaps @WardLT knows where to start on a fix?

P.S. Currently this test is being skipped on CircleCI

**Comment by WardLT** [comment]
The problem is probably that we do not clear the cache before the unit test. So, we're failing because the "cache_info" holds information from the previous stests.

I can fix it by adding some code that clears the cache to the unit test. Which branch should I issue a PR to?

Or, if it is easier for you to add it, the code looks like:

```python
# Reset the cache
_get_all_nearest_neighbors.cache_clear()
```

**Comment by ardunn** [comment]
@WardLT master is fine, ill merge as soon as it passes CI tests!
