### ISSUE TITLE
External Libraries and Matminer

### ISSUE THREAD

**Issue by WardLT** [hackingmaterials/matminer#378]
Issue #256 has caused me to continue thinking about our approach with building featurizers from external libraries. Do you think we should start breaking off featurizers that reference external libraries into their own submodules? 

So far, I think the answer is "no." Knowing the capabilities of the modules requires familiarity with the external libraries, and that outweighs the benefits of better recognizing external codes (our docs and citations methods handle this well) and any benefits from organizing (I'm starting to worry about the length of structure.py is interfering with maintainability). I also like that we use extra requirements for external libraries as it keeps matminer lighter weight, and brings further emphasis about the other codes (e.g., so people know about AMP and will judge if that code fits their needs better than matminer). 

I presume somebody else on this project has been mulling this over. Are external libraries worth discussing further at the moment?

**Comment by ardunn** [comment]
I've been thinking about this too.

Probably the easiest thing is to do what you proposed: just add a external.py module and put everything that requires external featurization libraries to be in there.

Alternatively, maybe a long-term solution would be to have each featurizer type be its own folder/subpackage, rather than submodule. For example:
```
featurizers
  structure
    __init.py (would import all classes from modules so syntax of notebooks etc. would remain same)
    symmetry.py (GlobalSymmetryFeatures, etc.)
    distribution.py (RadialDistributionFunction, etc.)
    bonding.py (SiteStatsFingerprint, BondFractions)
    matrix.py (CM, SCM, OFM)
    external.py (CGCNN, SOAP, etc.)
    misc.py (EwaldEnergy, etc.)
    conversions (StructureToIStructure, StructuretoComposition, etc.)
```

We could do the same thing for composition features. Wouldn't be much point in doing it for BS or DOS since there are only like 2-5 featurizers for each one in there.

**Comment by computron** [comment]
I like the idea of splitting up the featurizers as per @ardunn long-term solution

Shall we go for it?

Best,
Anubhav

**Comment by utf** [comment]
I like the idea of splitting the featurizers up too. I'd even go further and have separate files for each external code (e.g. `cgcnn.py` etc). As otherwise this is liable to get just as messy if more external codes are added.

**Comment by WardLT** [comment]
I agree with @utf about making a separate file for each external code

**Comment by computron** [comment]
Think we are all in agreement then!

**Comment by ardunn** [comment]
Sounds good to me. If anyone is implementing this my only request is that each __init__.py imports all featurizers so you can still do `from matminer.featurizers.structure import XYZFeaturizer`

This is important for (1) building the documentation featurizer table, (2) automatminer, and (3) just ease of use/not having long imports for stuff we commonly use

**Comment by computron** [comment]
+1, although not sure how to make sure people don't forget this. The only thing I can think of is some kind of automatic unit test that checks whether this was done using some kind of introspection
