### ISSUE TITLE
Capitalization consistency in feature names

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#38]
Hi all

I'd like to make the capitalization of feature names in matminer consistent. We can do:

* everything lower case (e.g. "band center") except for acroynms (e.g. "formation energy FERE") 
* first-word capitalization ("Formation Energy FERE")

I'm leaning towards the former, it's just easier to remember and type. The latter leads to some people deciding to do "Formation energy FERE" which is not the same ...

@WardLT @JFChen3 @nisse3000 

Thoughts, comments, etc?

**Comment by nisse3000** [comment]
No strong feelings towards anything.  My personal preference would actually be "Formation energy FERE" because I consider the labels/description to be something like a sentence.  I'd pick also the former otherwise because it's easier.

**Comment by WardLT** [comment]
I'm also in favor of all lower case except abbreviations. I agree, it is the easiest to remember and has fewer ambiguities (e.g., do I capitalize prepositions?).

**Comment by computron** [comment]
Thanks! Closed via 89c784f8933b6ca3fbb08684cb383b4685c3735d
