### ISSUE TITLE
Piezo and elastic data sets

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#39]
@kylebystrom 

I made some changes to the "datasets" package of matminer. Some require your attention:

- Note that git-lfs seemed to be a big hassle and so I decided to just remove it altogether. Hopefully a normal "pull" operation will just fix everything on your end, but if not you may need to re-clone. Let's skip git-lfs from now on unless it really seems necessary, sorry for the hassle but now we know.
- Note that I added tests to the package
- Note that I added a note of the original reference both in the CSV and method
- **Needs your attention**: The elastic_tensor dataset is nice in that it contains both formula and structure columns that can be used to generate descriptors. However, the "piezo" and "dielectric_constant" data sets don't have these columns (they are embedded in "meta"). Can you pull these columns out of meta, along with anything else that looks useful to have as its own column? You'll need to update the unit tests afterward. Make sure to preserve the comment line at top that gives the reference.

**Comment by computron** [comment]
Also if you can confirm that (i) I listed the correct references and (ii) the datasets I restored are correct (not out of date or anything from your latest commit) that would be helpful

**Comment by kylebystrom** [comment]
Yeah I'll look into this today and make those updates. I'll see if I can make the dataframes the exact same (i.e. the same columns). Sorry I didn't get the tests and references done when I first wrote up the datasets pacakge; I was rushing a bit too much.

Also, one of the reasons git lfs is useful (and why we will probably need a new repo or data storage repo if we do a bunch of big datasets) is that making big changes to big files can make the git log very large (e.g. every time I commit changes to the CSV files I could be changing like a MB of data, which all has to go into the git log). This is fine for just these three datasets if we can get them the way we want them and leave them that way, but we might want to get rid of the git log for those datasets to save space once we finalize them.

**Comment by computron** [comment]
Hi Kyle

Sure, we can use something like git BFG to clean out the logs later. I'll probably want to do this for some of the IPython notebooks too since those are really the biggest culprit. For now I think it's OK.

**Comment by kylebystrom** [comment]
It looks like the citations and data are good to go, except that you listed the dielectric paper as being 2017 when the link I originally downloaded it from says 2016. I'll fix that when I add the additional columns

**Comment by kylebystrom** [comment]
Hi @computron ,

I pulled the useful descriptors out of the meta dictionary for the piezoelectric and dielectric datasets, and I fixed the date for the dielectric citation. Everything should be up to date, but I saved an exact copy of the previous datasets in case something gets messed up.

**Comment by computron** [comment]
Thanks! I updated the unit tests

**Comment by kylebystrom** [comment]
Ah shoot sorry, I updated them too but forgot to push them. Thanks!
