### ISSUE TITLE
LFS File Issue (IPython notebooks): Missing Objects

### ISSUE THREAD

**Issue by kylebystrom** [hackingmaterials/matminer#42]
It appears that something is wrong with the MPDS and Citrine IPython notebooks.* I get the following output when I try to pull from the skeleton:

$ git lfs pull skeleton master
Git LFS: (0 of 2 files) 0 B / 191.73 KB 
Username for 'https://github.com': kylebystrom
Password for 'https://kylebystrom@github.com': 
Git LFS: (0 of 0 files, 2 skipped) 0 B / 0 B, 191.73 KB skipped                                                     [1f60dd7f710b54cf410b4215a740abc9b2e6eba0f92aadd5fd25046112c60094] Object does not exist on the server: [404] Object does not exist on the server
[13656b91a004cd765c2ad641c0efd741407b02aa382fce71ccbae96de51b48cc] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://github.com/hackingmaterials/matminer.git/info/lfs'

*I verified that the two missing files are in fact the MPDS and Citrine notebooks.

I don't need the notebooks right now, but this issue also prevents me pushing any updates to my fork, which is problematic. Does anyone else have this issue or know a fix?

Also, I noticed that not all of the notebooks are stored with git lfs. Is this intentional?

**Comment by computron** [comment]
Ideally we should have **nothing** be stored with git-lfs. I will try to fix in the next week but if there is anything I can do to help you fix it in the meantime let me know. I am not sure if this is a problem with your fork specifically or with main hackingmaterials/matminer, I would ensure it is the latter first.

**Comment by kylebystrom** [comment]
I could not fix my fork, but I did not have any important updates on it so I just deleted and remade the fork. Everything works now.
