### ISSUE TITLE
Request for PIEFACE site featurizer

### ISSUE THREAD

**Issue by mkhorton** [hackingmaterials/matminer#435]
J. Cumby and J. P. Attfield, Ellipsoidal Analysis of Coordination Polyhedra, Nature Communications 14235 (2017), see https://pieface.readthedocs.io/en/latest/ and https://github.com/jcumby/PIEFACE

Haven't investigated the easiest way to call it; suspect the most sensible option would be to call e.g. CrystalNN to get neighbor points and then their `Ellipsoid` class directly.

Feel free to close if this doesn't seem useful -- I don't have strong opinions, but seems like a nice supplement to other local env methods.

**Comment by ardunn** [comment]
@mkhorton were you imagining the ellipsoid parameters would be the output of this featurizer?

**Comment by mkhorton** [comment]
Yes, essentially the displacement from centre (of the centre atom from the ellipsoid centre), and the shape parameter (a measure of the ellipsoid distortion from ideal). Haven't looked into it much though; came across it when helping someone else trying to characterize their Jahn-Teller distortions.

**Comment by ardunn** [comment]
Superseded by #635
