### ISSUE TITLE
how to featurize 'material compostion' column

### ISSUE THREAD

**Issue by mlnjsh** [hackingmaterials/matminer#439]
I have  column  called  material composition  whose entries are as follows 

Ag10Cu35Zr55
Ag10Cu50Zr40

the numbers are proportions for example in Ag10Cu50Zr40  Ag is 10% Cu is 50% and  Zr is 40%

I want to separate composition and proportions from each entires 

any help would be highly appreciated

**Comment by WardLT** [comment]
Hello @mlnjsh ,

We have a support channel on https://discuss.matsci.org/c/matminer for questions on how to use matminer. 

Would you mind reposting there? We prefer to use GitHub issues to discuss errors and improvements to the software itself.
