### ISSUE TITLE
[Primitive]ToOxid[Primitive] conversions are slow

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/matminer#454]
Classes such as CompositionToOxidComposition and StructureToOxidStructure are quite slow. 

For example, adding oxidation states to compositions in "matbench_expt_gaps" which is ~4k samples is taking 20+ minutes on my laptop... there are also frequent parallelization problems where the conversion will just freeze, especially on larger datasets.

I understand this is based on the pymatgen methods, e.g., `Composition.add_charges_from_oxi_state_guesses`. 

Anyone @utf perhaps know of any easy ways we could speed it up?

**Comment by utf** [comment]
We have a way to speed up the oxidation state guessing in automatminer: 

https://github.com/hackingmaterials/automatminer/blob/c7b0251e22a6213eb61b5b0e9e8646d47f17c349/automatminer/featurization/core.py#L589-L594

In particular, the `max_sites=-50`, means it will try and reduce the composition to the minimum number of sites. The full docstring is:

```
            max_sites (int): if possible, will reduce Compositions to at most
                this many sites to speed up oxidation state guesses. If the
                composition cannot be reduced to this many sites a ValueError
                will be raised. Set to -1 to just reduce fully. If set to a
                number less than -1, the formula will be fully reduced but a
                ValueError will be thrown if the number of atoms in the reduced
                formula is greater than abs(max_sites).
```

I think we already tested and 50 sites gives a good tradeoff between time taken and number of compounds that fail.

**Comment by ardunn** [comment]
That seems sensible to me.

Even with that default, the Structure to oxid structure suffers from a similar problem. And both are prone to "freezing" on large dataframes

**Comment by computron** [comment]
Is the freezing related to the max_sites or unrelated? e.g., if you set max_sites to -10, does it still freeze? Or does the freezing not happen at that point?

**Comment by ardunn** [comment]
https://matsci.org/t/tips-on-reducing-computation-time/4457/5?u=ardunn
