### ISSUE TITLE
PropertyStats should include a "reduced mass" type average

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#46]
i.e., a parallel addition type term

1 / avg = 1 / x1 + 1 / x2 + 1 / x3 ...

Sometimes the "reduced mass" of a system can be more informative than an average mass for example

**Comment by WardLT** [comment]
Is this just the holder mean with n == -1? If so, we do already support this.

**Comment by computron** [comment]
The holder mean with n = -1 is pretty close, it is just the number of samples times what I originally suggested.

e.g. the reduced mass of a 2-body system with m1=2 and m2=2 is 1, whereas the holder mean is 2 (twice of 1, since we have 2 samples). I think the holder mean with n^-1 is closer to what I want since it generalizes better to >2 entries.
