### ISSUE TITLE
Progress bar option for load_dataframe_from_json and store_dataframe_as_json

### ISSUE THREAD

**Issue by janosh** [hackingmaterials/matminer#622]
Would be cool especially for large files if `load_dataframe_from_json` and `store_dataframe_as_json` both had a `pbar: bool = False` option that would display a progress bar while reading/writing to disk.

**Comment by ardunn** [comment]
@janosh this will be taken care of in #634

**Comment by utf** [comment]
is there a reason why the pbar is enabled by default? I use these functions in a lot of places where a progress bar is unexpected.

**Comment by ardunn** [comment]
@utf there is no reason besides making it easier for people who have never loaded a big dataframe from/to json to see what is going on. I am ok with changing it
