### ISSUE TITLE
Need local test to run on package on release before being uploaded to pypi

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/matminer#646]
Based on issue #644 with most recent release missing the .yaml file because the directory structure changed, we should have an automated way of checking the packaged distribution (uploaded to pypi) will pass all tests.

@utf do you know if there is a standard way to test the package to-be-distributed?

I think @computron has his own workflow for releasing matminer as I don't see any `twine` commands etc in the invoke `tasks.py` script, just a `python setup.py release` which looks like it puts everything into a command using a package like [releasecmd](https://pypi.org/project/releasecmd/). Maybe we can make part of the `publish` command to test the generated `sdist` or `wheel` in a new venv before uploading to pypi? Or we can include it in the CI

@computron do you have any thoughts?

**Comment by shyamd** [comment]
When you run the install in the workflow don't use an editable install. That will fix this as it forces the full setup.py to run and actually build the `MANIFEST` and copy files over.

**Comment by utf** [comment]
Would it be possible to release a new version? The one on pypi is still broken.

**Comment by ardunn** [comment]
> When you run the install in the workflow don't use an editable install. That will fix this as it forces the full setup.py to run and actually build the `MANIFEST` and copy files over.

Thanks @shyamd I will try this
