### ISSUE TITLE
Should pymongo actually be a requirement for matminer? 

### ISSUE THREAD

**Issue by jdagdelen** [hackingmaterials/matminer#653]
I have looked through the repo tree and it is never actually imported anywhere. Maybe this is left over from a previous version? 

@ardunn @computron

**Comment by ardunn** [comment]
That's a good point. It was originally in there to support this file:

https://github.com/hackingmaterials/matminer/blob/main/matminer/data_retrieval/retrieve_MongoDB.py


Getting data from arbitrary mongodbs (e.g., some custom atomate db) to a dataframe. I guess it is not technically _required_ to import or even test the package. I may change that to make the tests more complete (given CI can run mongo).
