### ISSUE TITLE
How to create dataset by users?

### ISSUE THREAD

**Issue by zcb-code** [hackingmaterials/matminer#688]
Matminer has an excellent performance in predicting mechanical properties. But in the example, the data set is loaded from website, not prepared by users. I want to know, how to prepare the training and predicting data sets? Is there any examples?

**Comment by ardunn** [comment]
Hi @zcb-code

First, for things not related to development of matminer, please post questions to the [MatSci forum](https://matsci.org/c/matminer/16). For further responses from me plz post your question there!

---
To answer your question:

On the matminer-examples repo, you can find examples of how to use matminer to create your own datasets by pulling from online repostories such as the materials project or your own custom mongodb databases.

Here's a link to the folder on data retrieval: https://github.com/hackingmaterials/matminer_examples/tree/main/matminer_examples/data_retrieval-nb

If you are more interested in creating your own datasets from files you have, such as POSCARs and CIFs along with your own computed or experimental properties, I'd recommend becoming familiar with how to handle materials data with [pymatgen](https://github.com/materialsproject/pymatgen) and how to use dataframes with [pandas](https://pandas.pydata.org/)
