### ISSUE TITLE
Recomputing the Voronoi Tessalation Repeatedly

### ISSUE THREAD

**Issue by CompRhys** [hackingmaterials/matminer#708]
I am trying to compare a new model to the ward-voronoi features on ~300k materials. Looking into the code it appears that each sub-featurizer of the feature set recalculated the voronoi tessalation itself. This means that the code runs ~5x slower than it might otherwise do.

I might be missing something but is there anyway that this can be restructured to allow or pre-computation? i.e. avoid calling this `nn = get_nearest_neighbors(VoronoiNN(weight=self.weight), strc, idx)` repeatedly by calculating it once and then passing around the nn object to the featurizers?

@WardLT

**Comment by ardunn** [comment]
@CompRhys do you have any ideas about how to implement this in pymatgen? or is there already a ticket open on pmg repo?
