### ISSUE TITLE
Conda install broken because of optional dscribe dependency being force installed on conda

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/matminer#764]
See:
- https://github.com/conda-forge/matminer-feedstock
- https://matsci.org/t/conda-install-broken/3427/26?u=ardunn

**Comment by jacksund** [comment]
@ardunn Thanks for opening this! I'm now helping maintain the matminer feedstock and have already fixed this issue [here](https://github.com/conda-forge/matminer-feedstock/pull/16). Still, I'll need to update the new dependencies that you just changed. Will you be making a new pypi release for these changes?

**Comment by ardunn** [comment]
Hey @jacksund yes I think we will! I still want to fix #740 before we make a new version but after that (should be today) we can make a new version and you can update the feedstock. Thanks again for the work in maintaining the conda install!

**Comment by ardunn** [comment]
I'll update this thread and tag you when we release a new version @jacksund

**Comment by ardunn** [comment]
@jacksund We have released a new version of matminer, might be worth checking the feedstock again to see if any problems come up

**Comment by jacksund** [comment]
@ardunn sorry, I forgot to respond to this earlier. But the update versions are available on conda-forge and everything looks good when installing them :+1:
