### ISSUE TITLE
some remaining items for DosFeaturizer

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#84]
@dyllamt @albalu 

* move to featurizers/dos.py (instead of bandstructure.py)
* the xbm_location_i should probably return fractional, not Cartesian coords. Can't think of any good reason for it to be Cartesian
* the coordination variable in ``get_cbm_vbm_scores`` is way too hacky. Only works for tet vs oct, uses a custom function, etc. Remove this var. If someone want this function they should code it well (works for multiple environments, etc), or keep it inside their own test code. Note that there is another issue open for a featurizer that takes in a site and returns back a string label for the coordination number of that site.
* get_cbm_vbm_scores() should explain in the docs what it's doing

**Comment by albalu** [comment]
@dyllamt , if you can add the doc to get_cbm_vbm_scores(), I can take care of the rest.

**Comment by dyllamt** [comment]
@albalu, that works for me. Maybe we can discuss more during our meeting today?

**Comment by dyllamt** [comment]
Remaining Issues:
- features stored in unordered, standard dictionary
- class attributes are initialized in the featurize() function
- feature_labels() can’t be called until after featurize() has been called

I'll work on fixing these in the next week. BandFeaturizer currently has the same issues.

**Comment by computron** [comment]
(this is completed)
