### ISSUE TITLE
Improving Performance of Composition Features

### ISSUE THREAD

**Issue by WardLT** [hackingmaterials/matminer#85]
I recently compared the performance of `matminer` to `Magpie` for computing composition-based features. For ~250k entries, `matminer` requires 24 minutes to evaluate the same features that take `Magpie` 4 seconds. 

From a quick profiling run, it seems like a fair amount of the time (25%) is spent retrieving elemental properties and, [surprisingly](https://github.com/scipy/scipy/issues/3035), computing the mode of a list. Digging further, the slow part of retrieving elemental properties is sorting the properties by atomic number and calling `Composition.get_el_amt_dict()`. My plan is to adjust the AbstractData API such that it is possible to avoid performing either of these operations.

I have opened this issue to see if anyone else has ideas for speeding up the code, and to let you know I am overhauling the AbstractData API. Let me know if I should make a public branch if you want to work on this together and we can avoid merge conflicts.

**Comment by computron** [comment]
Thanks for looking into this! I don't plan to work on this at the moment so don't need the public branch

**Comment by computron** [comment]
(this is completed)
