### ISSUE TITLE
revise unit tests for ChemEnvFingerprint

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#87]
@nisse3000 

See PR #86 for details

**Comment by nisse3000** [comment]
Hi @computron,
the CsCl structure is in fact distorted. The Cl atom/ion is not at the perfect center of the cube. And, the unit test features that (value smaller than 1 for both strategies).  I significantly increased the deviation from the perfect center position and I still get the same value for the simple and multi-weight strategy.  Apparently, both neighbor finding algorithms still find the same neighbors. Also, embedding in a 2x2x2 supercell didn't change the CSM values, but the computation started taking much more time. So, it doesn't seem that easy to find a case where the two differ. Do you know a small, yet very distorted structure in the MP database on top of your head?

**Comment by computron** [comment]
Ok if you distorted the structure and don't get different values, let's just forget it.
