### ISSUE TITLE
better (and working) tutorials

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#89]
better tutorials (e.g. show off featurize_dataframe, better use of featurizers, include structure featurizers, separate into “getting data”, “featurizing data”, and “full data mining workflow”, make sure they work with Py3 (no print ‘x’), use built-in example datasets for tutorials, etc.

**Comment by computron** [comment]
Note - I have created what should be a working Jupyter notebook for the initial intro.

Someone should go through the remaining tutorials and make sure they work ...

**Comment by albalu** [comment]
@montoyjh , when plotting in your tutorial, will you consider using figrecipes plotly wrappers? @ardunn and I are improving its defaults and adding 1-2 new plotly plots [here](https://github.com/ardunn/matminer/tree/viz) and would appreciate your feedback if you end up using any of them. We may be able to submit a PR within the next few days if you can wait with plotting as there will be some re-structuring.

**Comment by montoyjh** [comment]
Sure, that sounds great.

**Comment by montoyjh** [comment]
I'm also having a bit of trouble with accessing 2 of the tutorials via git-lfs, specifically MPDS_UO_bondlengths.ipynb and the one on PbTe bandgaps.  I can get them from the gists linked in the docs, if need be, but just wanted to mention it.

**Comment by computron** [comment]
@montoyjh We had lots of problems with git-lfs and tried our best to nuke git-lfs and all traces. Instead of git-lfs we wanted to do all the tutorials via gist - i.e., so they don't occupy space in the main repo, avoid the problems of git-lfs, but are still easy to access/modify/update/comment on. Was there some remnants of git-lfs left over?

**Comment by montoyjh** [comment]
Ah, great.

As far as gist, can I propose an alternative solution?  If you leave the notebooks in unexecuted form, they take up significantly less space (all of the notebooks take up around 100-200K, as opposed to 20-40M). If done this way, they can still be included in the repo.  When building the docs, you can run `jupyter nbconvert --to html --execute` which will execute the cells and export to html, which then would be copied to the _static folder and linked in docs.

Pros:
- Don't have to maintain external gists (i. e. one place for notebooks where they get fed into the docs directly)
- I can write a unit-test for the notebooks if they're on the main repo, to ensure the examples are working.

Cons:
- the exported HTML in the docs are still heavy (seems like roughly 50% of what the executed notebooks are).  Perhaps there's a way to not include these in the repo but still in the docs?

**Comment by computron** [comment]
Hi Joey

Feel free to try any better solution. My main concern is to not bloat the
repo with notebooks, plus all the various commit history of the notebooks
since each Jupyter notebook change can be big. It might be the same if the
HTML is just 50% of the executed notebook. Certainly small HTML files are
fine but a 20MB HTML is excessive ...

One potential workaround is something like this:

- keep the unexecuted notebooks in matminer repo
- have a script that executes that notebooks and pushes the HTML to a gist,
e.g., under the hackingmaterials organization.
- Link to the hackingmaterials gists in the docs.

Note that there might be a use case to still link to external gists. e.g.
if someone has some cool example of matminer, we can link to it without
putting in the main repo (doing the latter means that we need to support
that example for all time). But, it makes sense to have some core examples
within matminer.

Best,
Anubhav

**Comment by computron** [comment]
The tutorials have been fixed and moved to matminer_examples, I'm considering this closed; additional thoughts should go to the matminer_examples repo
