### ISSUE TITLE
New release 0.9.0?

### ISSUE THREAD

**Issue by ml-evs** [hackingmaterials/matminer#907]
Hi @ardunn, @computron and @hrushikesh-s, any objections if I make a new 0.9.0 release with the latest changes?

I've saved it as a draft for now: https://github.com/hackingmaterials/matminer/releases/tag/untagged-0b24d41be713249dfd44

The release contains several bugfixes, the testing overhaul and lots of dependency upgrades/compatibility fixes that I think would be useful to get out there. If I don't hear any objections in the few days, I'll just go for it.

**Comment by ardunn** [comment]
Good by me!

**Comment by janosh** [comment]
Thanks @ml-evs for [v0.9.0](https://github.com/hackingmaterials/matminer/releases/tag/v0.9.0)! Great to see you here. :)
