### ISSUE TITLE
compatibility request: pandas-2+

### ISSUE THREAD

**Issue by Youjin1985** [hackingmaterials/matminer#918]
**The reason I am are unable to use the Discourse forum in my ticket:
got message "Oops! That page doesn’t exist or is private" by following link https://discuss.matsci.org/c/matminer/automatminer**

Could you please make matminer compatible with pandas newer than 1.5.3? Its not fun to create another 1.2 Gb environment just because one package only compatible with  1.5.3.

**Comment by ml-evs** [comment]
Now that 0.9.2 is released you should be able to use matminer with pandas v2.
