### ISSUE TITLE
add BOP, AFS features

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#92]
Talk to @WardLT if interested

https://journals.aps.org/prb/abstract/10.1103/PhysRevB.95.144110

**Comment by computron** [comment]
maybe something for @kylebystrom ?

**Comment by dyllamt** [comment]
@computron, I did some reasearch into the structure features in above paper. I'm going to implement GRDF, incorporating PRDF into the featurizer, along with AFS. Summary below is mostly for my benifit.


PRDF (partial radial distribution function)  vector
- already implemented
- need to update return section of doc

GRDF (general radial distribution function)  vector
- similar to AGNIFingerprints
- PRDF and AGNIFingerprints (baring direction resolved features) could be implemented inside of GRDF
- GRDF uses a generalized distance functional for binning (atom can belong to more than one bin, and its weight need not be one)
- suggested bins: gaussians, trig functions, bessel functions
- should implement site-wise not element-pair-wise

AFS (angular fourier series)  2x2 matrix
- also uses generalized distance metrics (could share with GRDF)
- each element is two generalized distance metrics multiplied by angle

BOP (bond orientation parameter)  vector
- first few terms implemented as q2, q4, and q6 in OPSiteFingerprint
- metric for nearest neighbor enviornments

**Comment by WardLT** [comment]
Thanks for looking in to this, @dyllamt ! 

I agree, having a GRDF class would cover all of these use cases quite nicely. I'm worried how expansive the number of options for that class might become to cover all of these types of radial distribution functions. Have you already considered making featurizers for PRDF/RDF subclasses of GRDF, or creating clearly-defined presets for common types of GRDF's (e.g., the PRDF)?

**Comment by dyllamt** [comment]
I like the subclass suggestion @WardLT .

The parent and child classes could share the same _featurize_() function, but have different _init_() for defining the bins--GRDF would have a list of bin functions as inputs, while PRDF would only have a cutoff and binsize as currently implemented.

RDF could be implemented as an option with a boolean flag, which specifies whether to sum the PRDFs for each site.

**Comment by dyllamt** [comment]
@computron 

I think we can close this issue. There are some wrinkles getting ironed out with multiprocessing, but AFS and GRDF were implemented in pull request #138

**Comment by computron** [comment]
Ok closing

Will weigh in on the other stuff later, I try to do most code reviews Friday.
