### ISSUE TITLE
Re-enable tests that are skipped in CI

### ISSUE THREAD

**Issue by ml-evs** [hackingmaterials/matminer#923]
#922 disables some tests as they do not work with the latest numpy/pandas combo. This may be because the test code itself is broken, or bad numpy/pandas calls are being made in the featurizer or an upstream dep.

**Comment by JaGeo** [comment]
@ml-evs Should one also dis-enable the corresponding featurizers as well for now?
See https://github.com/hackingmaterials/matminer/issues/915#issuecomment-1933160620

**Comment by ml-evs** [comment]
> @ml-evs Should one also dis-enable the corresponding featurizers as well for now?
> See https://github.com/hackingmaterials/matminer/issues/915#issuecomment-1933160620

Yeah I think that's next on the list, I just want to verify that it's not the test cases themselves that are the problem first
