### ISSUE TITLE
`ChemEnvSiteFingerprint.from_preset()` bug for coordination environments with `deactivate=True` or `points=None`

### ISSUE THREAD

**Issue by kaueltzen** [hackingmaterials/matminer#945]
Hi, 

the `ChemEnvSiteFingerprint.from_preset()` computes the csm for a list of coordination environments (ces) in `cetypes`.
However, some of the ces listed there are not implemented geometries in the `LocalGeometryFinder()`, e.g., because their `deactivate` attribute is True (e.g., SH:11) or because their `points` attribute is None (e.g., S:10).
This causes a `KeyError` in ChemEnv
https://github.com/materialsproject/pymatgen/blob/ea7c3390e2db99a35f3eee242073ffc2830bbd4c/src/pymatgen/analysis/chemenv/coordination_environments/structure_environments.py#L2077

The issue was already reported in https://matsci.org/t/help-with-using-chemenvsitefingerprint/52628 and maybe also in https://matsci.org/t/key-error-in-chemenvsitefingerprint-function/4020 .

Proposed solutions:
1. After instantiating the LocalGeometryFinder in https://github.com/hackingmaterials/matminer/blob/8e99cf6c531588b79abfbcbf734fac49ce3914a7/matminer/featurizers/site/fingerprint.py#L796 one could get the available ces directly from the lgf and eliminate the items from `ce_list` that are not implemented there before instantiating the `ChemEnvSiteFingerprint()`. This would work indepently from the pymatgen version.
2. A shorter fix would be to directly remove the affected ces from `cetypes` as probably the `deactivate` attribute is not going to be changed to `False` in existing coordination geometry files in future pymatgen versions(?).

I'm happy to implement one of the solutions if you are interested.

**Comment by JaGeo** [comment]
Would you be happy to merge a fix for this, @ml-evs ? Thanks in advance for your time.

**Comment by ml-evs** [comment]
I don't know enough about this part of the code to know what the best fix is without more digging, but I'll happily review a PR with a test case!
