### ISSUE TITLE
Add a BagofBonds structure featurizer

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#97]
This would take in a structure and retain a list that contains the number of bonds (probably as fraction). For example, if a structure had 2 Li-O bonds and 3 Li-P bonds, it could return [0.4, 0.6] as the featurizer value and ["Li-O", "Li-P"] as the feature labels.

Some aspects to note:
* You probably want to allow any pymatgen NearNeighbor class to be used as the bond detection method. Some presets might help with usage
* If you are featurizing an entire data frame, you need the feature labels to match and be a concatenation of all the bonds in all the various structures in the data frame. Also some complications if you fit a model and then predict a structure for which there are no bonds in the training set. Some hashing tricks from text mining might help with this. Talk to AJ if you are implementing and this is confusing to you.

**Comment by ardunn** [comment]
this is done (excluding hashing tricks)
